### ISSUE TITLE
Error "Unexpected token" if file contains BOM header

### ISSUE THREAD

**Issue by agelenava** [thaggie/gulp-json-transform#6]
In case I store file with 'UTF-8 with signature' and this file contains BOM header, the plugin throws an error 'Unexpected token'.

I found this answer http://stackoverflow.com/a/24376813/1545679 
It looks like it could be fixed in the plugin. 

Could you help me? 
Thanks in advance.

**Comment by thaggie** [comment]
I think [gulp-bom](https://www.npmjs.com/package/gulp-bom) should be what you want.
